spring:
  application:
    name: "carrybasar"
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    properties:
      schema: transportsschema
  mail:
    host: smtp.mailersend.net
    port: 587
    username: MS_jiVq6W@test-yxj6lj9zpz74do2r.mlsender.net
    password: mssp.9pvKbPR.0p7kx4xn3j8g9yjr.ZoBAJFZ
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls.enable: true
          # Opcional: evita warnings de certificado
          ssl.trust: smtp.mailersend.net
      # Solo en desarrollo: log completo del diálogo SMTP
      # mail.properties.mail.debug: true

server:
  port: 8080

security:
  jwt:
    secret-key: dca58f1c946f7b7ca8cfdb1c04201783b323dd281ab8be2af81db63798e8a4d4
    expiration-time: 3600000

